# -*- coding: utf-8 -*-
from odoo import api, fields, models, tools, _

class Partner(models.Model):
    _inherit = 'res.partner'

    hs_company_id = fields.Integer(string='HS Company ID')
    hs_create_date = fields.Date(string='HS Create Date')
    hs_last_modified_date = fields.Date(string='HS Last Modified Date')
    hs_lastupdated = fields.Date(string='HS LastUpdated')
    hs_first_contact_create_date = fields.Date(string='HS First Contact Create Date')
    hs_first_deal_created_date = fields.Date(string='HS First Deal Created Date')
    company_email_domain_name = fields.Char(string='Company Email Domain Name')
    company_news = fields.Char(string='Company News')
    hs_lead_status = fields.Char(string='HS Lead Status')
    hs_subscription_status = fields.Char(string='HS Subscription Status')
    hs_bio_convention_status = fields.Char(string='HS BIO Convention Status')
    sub_sub_industry = fields.Char(string='Sub Sub Industry')
    hscontact_region = fields.Char(string='HScontact Region')
    sic_description = fields.Char(string='SIC Description')
    naics_description = fields.Char(string='NAICS Description')
    duns_number = fields.Char(string='D-U-N-S Number')
    hs_company_owner = fields.Char(string='HS Company owner')
    hs_owner_assigned_date = fields.Date(string='HS Owner Assigned Date')
    ip_address = fields.Char(string='IP Address')
    ip_city = fields.Char(string='IP City')
    ip_state_region = fields.Char(string='IP State/Region')
    ip_country = fields.Char(string='IP Country')
    ip_timezone = fields.Char(string='IP Timezone')
    year_founded = fields.Char(string='Year Founded')
    employees = fields.Char(string='Employees')
    annual_revenue = fields.Char(string='Annual Revenue')
    total_revenue = fields.Char(string='Total Revenue')
    ownership = fields.Char(string='Ownership')
    ticker = fields.Char(string='Ticker')
    market_capitalization_millions = fields.Char(string='Market Capitalization Millions')
    total_money_raised = fields.Char(string='Total Money Raised')
    last_funding_round = fields.Char(string='Last Funding Round')
    using_sharepoint = fields.Char(string='Using SharePoint')
    sharepoint_version = fields.Char(string='SharePoint Version')
    currently_with_competitor = fields.Char(string='Currently With Competitor')
    competitor_expiration_date = fields.Date(string='Competitor Expiration Date')
    indications = fields.Char(string='Indications')
    primary_therapy_areas = fields.Char(string='Primary Therapy Areas')
    secondary_therapy_areas = fields.Char(string='Secondary Therapy Areas')
    sub_sector = fields.Char(string='Sub-Sector')
    product_area = fields.Char(string='Product Area')
    products_managed = fields.Char(string='Products Managed')
    primary_product = fields.Char(string='Primary Product')
    dev_phase = fields.Char(string='Dev Phase')
    products_in_dev = fields.Char(string='Products In Dev')
    number_of_products_in_development = fields.Char(string='Number of Products in Development')
    products_on_market = fields.Char(string='Products on Market')
    number_of_products_on_the_market = fields.Char(string='Number of Products on the Market')
    licensing_status = fields.Char(string='Licensing Status')
    assetname = fields.Char(string='AssetName')
    assettype = fields.Char(string='AssetType')
    linkedin_company_page = fields.Char(string='LinkedIn Company Page')
    facebook_company_page = fields.Char(string='Facebook Company Page')
    hs_number_of_blockers = fields.Char(string='HS Number of blockers')
    hs_number_of_contacts_with_a_buying_role = fields.Char(string='HS Number of contacts with a buying role')
    hs_number_of_decision_makers = fields.Char(string='HS Number of decision makers')
    hs_number_of_open_deals = fields.Char(string='HS Number of open deals')
    hs_number_of_times_contacted = fields.Char(string='HS Number of times contacted')
    hs_number_of_pageviews = fields.Char(string='HS Number of Pageviews')
    hs_number_of_sessions = fields.Char(string='HS Number of Sessions')
    hs_number_of_form_submissions = fields.Char(string='HS Number of Form Submissions')
    hs_time_of_first_session = fields.Char(string='HS Time of First Session')
    hs_first_touch_converting_campaign = fields.Char(string='HS First Touch Converting Campaign')
    hs_first_conversion = fields.Char(string='HS First Conversion')
    hs_first_conversion_date = fields.Date(string='HS First Conversion Date')
    hs_last_activity_date = fields.Date(string='HS Last Activity Date')
    hs_last_sales_activity_date = fields.Date(string='HS Last Sales Activity Date')
    hs_last_open_task_date = fields.Date(string='HS Last Open Task Date')
    hs_last_logged_call_date = fields.Date(string='HS Last Logged Call Date')
    hs_last_contacted = fields.Date(string='HS Last Contacted')
    hs_last_booked_meeting_date = fields.Date(string='HS Last Booked Meeting Date')
    hs_time_last_seen = fields.Date(string='HS Time Last Seen')
    hs_last_touch_converting_campaign = fields.Char(string='HS Last Touch Converting Campaign')
    hs_lead_source = fields.Char(string='HS Lead Source')
    hs_lead_source_description = fields.Char(string='HS Lead Source Description')
    hs_opportunity_stage = fields.Char(string='HS Opportunity Stage')
    use_technology_share_documents = fields.Char(string='Do you currently use a technology solution to share confidential documents with third parties?')
    how_many_deals = fields.Char(string='How many M&A deals is your organization likely to be involved in during the next twelve months?')
    hs_became_an_other_lifecycle_date = fields.Date(string='HS Became an Other Lifecycle Date')
    hs_became_a_subscriber_date = fields.Date(string='HS Became a Subscriber Date')
    hs_became_a_lead_date = fields.Date(string='HS Became a Lead Date')
    hs_became_a_marketing_qualified_lead_date = fields.Date(string='HS Became a Marketing Qualified Lead Date')
    hs_became_a_sales_qualified_lead_date = fields.Date(string='HS Became a Sales Qualified Lead Date')
    hs_became_an_opportunity_date = fields.Date(string='HS Became an Opportunity Date')
    hs_became_a_customer_date = fields.Date(string='HS Became a Customer Date')
    hs_became_an_evangelist_date = fields.Date(string='HS Became an Evangelist Date')
    hs_first_deal_created_date = fields.Date(string='HS First Deal Created Date')
    msa_agreement = fields.Boolean(string='MSA Agreement')
    sharevault_usage_begin_date = fields.Date(string='ShareVault Usage Begin Date')
    hs_associated_contacts = fields.Char(string='HS Associated Contacts')
    hs_associated_deals = fields.Char(string='HS Associated Deals')
    hs_total_open_deal_value = fields.Char(string='HS Total open deal value')
    hs_associated_company_id = fields.Integer(string='HS Associated Company ID')
    hs_associated_company = fields.Char(string='HS Associated Company')
    hs_associated_contacts = fields.Char(string='HS Associated Contacts')
    data_last_updated = fields.Date(string='Data Last Updated')
    hs_account_status = fields.Char(string='HS Account Status')
