# -*- coding: utf-8 -*-
from odoo import api, fields, models, tools, _

class Partner(models.Model):
    _inherit = 'res.partner'

    hs_company_id = fields.Integer(string='HS Company ID')
    hs_create_date = fields.Date(string='HS Create Date')
    hs_last_modified_date = fields.Date(string='HS Last Modified Date')
    hs_lastupdated = fields.Date(string='HS LastUpdated')
    hs_first_contact_create_date = fields.Date(string='HS First Contact Create Date')
    hs_first_deal_created_date = fields.Date(string='HS First Deal Created Date')
    hs_lead_status = fields.Char(string='HS Lead Status')
    hs_subscription_status = fields.Char(string='HS Subscription Status')
    hs_bio_convention_status = fields.Char(string='HS BIO Convention Status')
    hs_company_owner = fields.Char(string='HS Company owner')
    hs_owner_assigned_date = fields.Date(string='HS Owner Assigned Date')
    hs_number_of_blockers = fields.Char(string='HS Number of blockers')
    hs_number_of_contacts_with_a_buying_role = fields.Char(string='HS Number of contacts with a buying role')
    hs_number_of_decision_makers = fields.Char(string='HS Number of decision makers')
    hs_number_of_open_deals = fields.Char(string='HS Number of open deals')
    hs_number_of_times_contacted = fields.Char(string='HS Number of times contacted')
    hs_number_of_pageviews = fields.Char(string='HS Number of Pageviews')
    hs_number_of_sessions = fields.Char(string='HS Number of Sessions')
    hs_number_of_form_submissions = fields.Char(string='HS Number of Form Submissions')
    hs_time_of_first_session = fields.Char(string='HS Time of First Session')
    hs_first_touch_converting_campaign = fields.Char(string='HS First Touch Converting Campaign')
    hs_first_conversion = fields.Char(string='HS First Conversion')
    hs_first_conversion_date = fields.Date(string='HS First Conversion Date')
    hs_last_activity_date = fields.Date(string='HS Last Activity Date')
    hs_last_sales_activity_date = fields.Date(string='HS Last Sales Activity Date')
    hs_last_open_task_date = fields.Date(string='HS Last Open Task Date')
    hs_last_logged_call_date = fields.Date(string='HS Last Logged Call Date')
    hs_last_contacted = fields.Date(string='HS Last Contacted')
    hs_last_booked_meeting_date = fields.Date(string='HS Last Booked Meeting Date')
    hs_time_last_seen = fields.Date(string='HS Time Last Seen')
    hs_last_touch_converting_campaign = fields.Char(string='HS Last Touch Converting Campaign')
    hs_lead_source = fields.Char(string='HS Lead Source')
    hs_lead_source_description = fields.Char(string='HS Lead Source Description')
    hs_opportunity_stage = fields.Char(string='HS Opportunity Stage')
    hs_became_an_other_lifecycle_date = fields.Date(string='HS Became an Other Lifecycle Date')
    hs_became_a_subscriber_date = fields.Date(string='HS Became a Subscriber Date')
    hs_became_a_lead_date = fields.Date(string='HS Became a Lead Date')
    hs_became_a_marketing_qualified_lead_date = fields.Date(string='HS Became a Marketing Qualified Lead Date')
    hs_became_a_sales_qualified_lead_date = fields.Date(string='HS Became a Sales Qualified Lead Date')
    hs_became_an_opportunity_date = fields.Date(string='HS Became an Opportunity Date')
    hs_became_a_customer_date = fields.Date(string='HS Became a Customer Date')
    hs_became_an_evangelist_date = fields.Date(string='HS Became an Evangelist Date')
    hs_first_deal_created_date = fields.Date(string='HS First Deal Created Date')
    hs_associated_contacts = fields.Char(string='HS Associated Contacts')
    hs_associated_deals = fields.Char(string='HS Associated Deals')
    hs_total_open_deal_value = fields.Char(string='HS Total open deal value')
    hs_associated_company_id = fields.Integer(string='HS Associated Company ID')
    hs_associated_company = fields.Char(string='HS Associated Company')
    hs_associated_contacts = fields.Char(string='HS Associated Contacts')
    hs_account_status = fields.Char(string='HS Account Status')
    hscontact_region = fields.Char(string='HScontact Region')
    hs_contact_id = fields.Integer(string='HS Contact ID')
    hs_marketing_emails_bounced = fields.Integer(string='HS Marketing emails bounced')
    hs_marketing_emails_delivered = fields.Integer(string='HS Marketing emails delivered')
    hs_marketing_emails_opened = fields.Integer(string='HS Marketing emails opened')
    hs_marketing_emails_clicked = fields.Integer(string='HS Marketing emails clicked')
    hs_email_hard_bounce_reason = fields.Char(string='HS Email hard bounce reason')
    hs_forced_sync_to_sfdc = fields.Boolean(string='HS Forced Sync to SFDC')
    hs_contact_owner = fields.Char(string='HS Contact owner')
    hs_original_source = fields.Char(string='HS Original Source')
    hs_original_source_drill_down_1 = fields.Char(string='HS Original Source Drill-Down 1')
    hs_original_source_drill_down_2 = fields.Char(string='HS Original Source Drill-Down 2')
    hs_recycled_flag_marketing = fields.Boolean(string='HS Recycled flag (Marketing)')
    hs_unqualified_reason = fields.Char(string='HS Unqualified Reason')
    hs_no_sales_calls = fields.Boolean(string='HS No Sales Calls')
    hs_affiliations = fields.Char(string='HS Affiliations')
    hs_affiliate_contact = fields.Char(string='HS Affiliate Contact')
    hs_regional_affiliate = fields.Char(string='HS Regional Affiliate')
    hs_predictive_lead_score = fields.Char(string='HS Predictive Lead Score')
    hs_lifecycle_stage = fields.Char(string='HS Lifecycle Stage')
    hs_mql_type = fields.Char(string='HS MQL Type')
    hs_mql_type_date = fields.Date(string='HS MQL Type Date')
    hs_mql_date = fields.Date(string='HS MQL Date')
    hs_lead_rating = fields.Char(string='HS Lead Rating')
    hs_i_agree_to_the_msa = fields.Char(string='HS I agree to the MSA')
    hs_recent_conversion = fields.Char(string='HS Recent Conversion')
    hs_recent_conversion_date = fields.Char(string='HS Recent Conversion Date')
    hs_time_first_seen = fields.Date(string='HS Time First Seen')
    hs_sends_since_last_engagement = fields.Integer(string='HS Sends Since Last Engagement')
    hs_time_of_last_session = fields.Date(string='HS Time of Last Session')
    hs_average_pageviews = fields.Char(string='HS Average Pageviews')
    hs_first_page_seen = fields.Char(string='HS First Page Seen')
    hs_last_page_seen = fields.Char(string='HS Last Page Seen')
    hs_number_of_event_completions = fields.Integer(string='HS Number of event completions')
    hs_number_of_unique_forms_submitted = fields.Integer(string='HS Number of Unique Forms Submitted')
    hs_total_number_of_zoom_webinar_registrations = fields.Integer(string='HS Total number of Zoom webinar registrations')
    hs_total_number_of_zoom_webinars_attended = fields.Integer(string='HS Total number of Zoom webinars attended')
    hs_last_registered_zoom_webinar = fields.Char(string='HS Last registered Zoom webinar')
    hs_average_zoom_webinar_attendance_duration = fields.Char(string='HS Average Zoom webinar attendance duration')
    hs_linkedin_clicks = fields.Integer(string='HS LinkedIn Clicks')
    hs_twitter_clicks = fields.Integer(string='HS Twitter Clicks')
    hs_facebook_clicks = fields.Integer(string='HS Facebook Clicks')
    hs_google_plus_clicks = fields.Integer(string='HS Google Plus Clicks')
    hs_broadcast_clicks = fields.Integer(string='HS Broadcast Clicks')
    hs_number_of_sales_activities = fields.Integer(string='HS Number of Sales Activities')
    hs_associated_company_id = fields.Integer(string='HS Associated Company ID')
    hs_associated_company = fields.Char(string='HS Associated Company')
    hubspot_score = fields.Integer(string='HubSpot Score')

    sv_role = fields.Char(string='SV Role')
    zoomcontactid = fields.Char(string='ZoomContactID')
    linkedin_source = fields.Char(string='LinkedIn Source')
    linkedin_bio = fields.Char(string='LinkedIn Bio')
    linkedin_connections = fields.Char(string='LinkedIn Connections')
    twitter_username = fields.Char(string='Twitter Username')
    twitter_bio = fields.Char(string='Twitter Bio')
    twitter_profile_photo = fields.Char(string='Twitter Profile Photo')
    follower_count = fields.Char(string='Follower Count')
    klout_score = fields.Char(string='Klout Score')
    interested_learning = fields.Boolean(string="I'm interested in learning how to share our documents securely with external parties.")
    salesforce_campaign_ids = fields.Char(string='Salesforce Campaign IDs')
    department = fields.Char(string='Department')
    company_email_domain_name = fields.Char(string='Company Email Domain Name')
    company_news = fields.Char(string='Company News')
    sub_sub_industry = fields.Char(string='Sub Sub Industry')
    sic_description = fields.Char(string='SIC Description')
    naics_description = fields.Char(string='NAICS Description')
    duns_number = fields.Char(string='D-U-N-S Number')
    ip_address = fields.Char(string='IP Address')
    ip_city = fields.Char(string='IP City')
    ip_state_region = fields.Char(string='IP State/Region')
    ip_country = fields.Char(string='IP Country')
    ip_timezone = fields.Char(string='IP Timezone')
    year_founded = fields.Char(string='Year Founded')
    employees = fields.Char(string='Employees')
    annual_revenue = fields.Char(string='Annual Revenue')
    total_revenue = fields.Char(string='Total Revenue')
    ownership = fields.Char(string='Ownership')
    ticker = fields.Char(string='Ticker')
    market_capitalization_millions = fields.Char(string='Market Capitalization Millions')
    total_money_raised = fields.Char(string='Total Money Raised')
    last_funding_round = fields.Char(string='Last Funding Round')
    using_sharepoint = fields.Char(string='Using SharePoint')
    sharepoint_version = fields.Char(string='SharePoint Version')
    currently_with_competitor = fields.Char(string='Currently With Competitor')
    competitor_expiration_date = fields.Date(string='Competitor Expiration Date')
    indications = fields.Char(string='Indications')
    primary_therapy_areas = fields.Char(string='Primary Therapy Areas')
    secondary_therapy_areas = fields.Char(string='Secondary Therapy Areas')
    sub_sector = fields.Char(string='Sub-Sector')
    product_area = fields.Char(string='Product Area')
    products_managed = fields.Char(string='Products Managed')
    primary_product = fields.Char(string='Primary Product')
    dev_phase = fields.Char(string='Dev Phase')
    products_in_dev = fields.Char(string='Products In Dev')
    number_of_products_in_development = fields.Char(string='Number of Products in Development')
    products_on_market = fields.Char(string='Products on Market')
    number_of_products_on_the_market = fields.Char(string='Number of Products on the Market')
    licensing_status = fields.Char(string='Licensing Status')
    assetname = fields.Char(string='AssetName')
    assettype = fields.Char(string='AssetType')
    linkedin_company_page = fields.Char(string='LinkedIn Company Page')
    facebook_company_page = fields.Char(string='Facebook Company Page')
    use_technology_share_documents = fields.Char(string='Do you currently use a technology solution to share confidential documents with third parties?')
    how_many_deals = fields.Char(string='How many M&A deals is your organization likely to be involved in during the next twelve months?')
    msa_agreement = fields.Boolean(string='MSA Agreement')
    sharevault_usage_begin_date = fields.Date(string='ShareVault Usage Begin Date')
    data_last_updated = fields.Date(string='Data Last Updated')
